// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// TodoHandler is an autogenerated mock type for the TodoHandler type
type TodoHandler struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: c
func (_m *TodoHandler) CreateTask(c *gin.Context) {
	_m.Called(c)
}

// FetchListTodo provides a mock function with given fields: c
func (_m *TodoHandler) FetchListTodo(c *gin.Context) {
	_m.Called(c)
}

type mockConstructorTestingTNewTodoHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewTodoHandler creates a new instance of TodoHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTodoHandler(t mockConstructorTestingTNewTodoHandler) *TodoHandler {
	mock := &TodoHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
